/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
  const ElLoading: typeof import('element-plus/es')['ElLoading']
  const ElMessage: typeof import('element-plus/es')['ElMessage']
  const ElMessageBox: typeof import('element-plus/es')['ElMessageBox']
  const ElOption: typeof import('element-plus/es')['ElOption']
  const ElPopover: typeof import('element-plus/es')['ElPopover']
  const ElPopoverDirective: typeof import('element-plus/es')['ElPopoverDirective']
  const ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
  const ElTabPane: typeof import('element-plus/es')['ElTabPane']
  const ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
  const vLoading: typeof import('element-plus/es')['ElLoadingDirective']
}
